### ISSUE TITLE
Thumbnail label possitioning.

### ISSUE THREAD

**Issue by amcnulty** [amcnulty/Basic-Portfolio#1]
The labels for the thumbnails on the profile page are not positioned correctly when viewed on Firefox or IE.

![image](https://user-images.githubusercontent.com/8146225/29546498-abc8a748-86a9-11e7-82ca-5b9166f82cdf.png)

When viewed in chrome it is correct.

![image](https://user-images.githubusercontent.com/8146225/29546517-c3a19f14-86a9-11e7-9acc-2c57c4a7b1d3.png)

**Comment by amcnulty** [comment]
I found a fix for this.

Here was the css code for the labels before the fix.

```css
.label {
    position: absolute;
    bottom: 20px;
    height: 60px;
    line-height: 60px;
    width: 100%;
    text-align: center;
    color: white;
    font-size: 1.2em;
    background-color: rgba(74, 170, 165, .7);
}
```

Here is the new code. All I added was a left property to the label.

```css
.label {
    position: absolute;
    bottom: 20px;
    left: 0px;
    height: 60px;
    line-height: 60px;
    width: 100%;
    text-align: center;
    color: white;
    font-size: 1.2em;
    background-color: rgba(74, 170, 165, .7);
```
