### ISSUE TITLE
Social Icon Hovering

### ISSUE THREAD

**Issue by amcnulty** [amcnulty/Basic-Portfolio#3]
I want a clean way to have two icon images stacked on top of each other and when they are hovered over the top one transitions it's opacity to 0 revealing the bottom one. Currently this is working and is cross-browser compatible, however, it is hard coded for this site. I want something that will work cross-browser and is easily duplicated for future projects.

**Comment by amcnulty** [comment]
To make this work better I came up with this fix.

## HTML

Here is the html structure for the entire link with both containers for the color change. In this case I have a black Github icon that transitions to red when hovered.

```
<a href="https://github.com/amcnulty" class="socialIcon">
    <div id="gitHubIconRed"></div>
    <div id="gitHubIconBlack"></div>
</a>
```
## CSS

Here is the css to make this happen.

```css
.socialIcon {
    position: relative;
    display: inline-block;
    width: 60px;
    height: 60px;
}

.socialIcon div {
    position: absolute;
    top: 0px;
    left: 0px;
    width: 60px;
    height: 60px;
}

#gitHubIconBlack {
    background-image: url("../images/icon/github_black.png");
    background-size: contain;
    transition: opacity .3s ease;
}

#gitHubIconRed {
    background-image: url("../images/icon/github_red.png");
    background-size: contain;
}

#gitHubIconBlack:hover {
    opacity: 0;
}
```

This is pretty simple and works cross-browser. The nice thing about it is that you can move around the anchor element to where it needs to be on the page and the whole button with the transition effect will go with it.
